apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-plugin-auto-backup-pro-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: select
          label: 按天/小时
          name: timeUnit
          validation: required
          value: 'DAY'
          options:
            - label: 小时
              value: HOUR
            - label: 天
              value: DAY
        - $formkit: select
          label: 时间间隔
          name: interval
          validation: required|Number
          value: 3
          action: /apis/autobackup.wangwenzhu.cn/v1alpha1/config-interval
          requestOption:
            method: GET
        - $formkit: select
          label: 备份最大保存数量
          name: maxBackupCount
          validation: required
          value: 5
          options:
            - label: 1
              value: 1
            - label: 2
              value: 2
            - label: 3
              value: 3
            - label: 4
              value: 4
            - label: 5
              value: 5
    - group: cos
      label: COS配置
      formSchema:
        - $formkit: checkbox
          label: 启用 COS 上传
          name: enabled
          id: enabled
          key: enabled
          value: false
        - $formkit: text
          label: 地域
          name: region
          key: region
          value: ''
          validation: required
          if: $get(enabled).value === true
        - $formkit: password
          label: SecretId
          name: secretId
          key: secretId
          value: ''
          validation: required
          if: $get(enabled).value === true
        - $formkit: password
          label: SecretKey
          name: secretKey
          key: secretKey
          value: ''
          validation: required
          if: $get(enabled).value === true
        - $formkit: text
          label: 存储桶名称
          name: bucketName
          key: bucketName
          value: ''
          validation: required
          if: $get(enabled).value === true
        - $formkit: text
          label: 上传路径
          name: uploadPath
          key: uploadPath
          value: ''
          validation: required
          placeholder: 例:halo/backup/
          help: 备份文件目录格式：上传路径/${year}/${month}
          if: $get(enabled).value === true
        - $formkit: checkbox
          label: 删除旧的备份文件
          name: deleteOld
          id: deleteOld
          key: deleteOld
          value: false
          if: $get(enabled).value === true
        - $formkit: select
          label: 备份最大保存数量
          name: maxCosBackupCount
          validation: required|Number
          value: 3
          action: /apis/autobackup.wangwenzhu.cn/v1alpha1/config-interval
          requestOption:
            method: GET
          if: $get(deleteOld).value === true